--1. CREACIÓN DE LA TABLA.
--A. DEFINICIÓN DE LA ESTRUCTURA DE DATOS PARA LA CARGA DEL CSV.

CREATE TABLE ecommerce_transactions (
    venta_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(20) NOT NULL,
    stock_code VARCHAR(20) NOT NULL,
    description TEXT,
    quantity INT NOT NULL,
    -- SE CARGA COMO VARCHAR PORQUE POSTGRESQL INTERPRETA LAS FECHAS COMO YYYY-MM-DD,
    -- Y EL DATASET NO RESPETA ESE ORDEN. SE EVITAN ASÍ ERRORES AL CARGAR EL CSV
    -- (LA CONVERSIÓN A TIMESTAMP SE HACE MÁS ABAJO CON ALTER TABLE).
    invoice_date VARCHAR(50) NOT NULL,   
    unit_price NUMERIC(10,2) NOT NULL,
    customer_id INT,
    country VARCHAR(100) NOT NULL
);

--B. UTILIZAMOS LA FUNCIÓN ALTER TABLE PARA LOGRAR CONVERTIR LA COLUMNA "invoice_date" DE VARCHAR A TIMESTAMP, DICIÉNDOLE A POSTGRESQL QUE ORDEN DEBE DE SEGUIR PARA EVITAR ERRORES DE CARGA. 

ALTER TABLE ecommerce_transactions 
  ALTER COLUMN invoice_date TYPE TIMESTAMP 
  USING to_timestamp(invoice_date, 'MM/DD/YYYY HH24:MI');
